# Server
server:
  port: 15000
  error:
    include-exception: false
    include-stacktrace: never

# General
general:
  domain: localhost

# Spring
spring:
  # Webflux
  webflux:
    base-path: /
    static-path-pattern: /static/**

# Security
security:
  cors:
    max-age: 3600
    allowed-origin-patterns:
      - http://localhost:*
  jwt:
    issuer: ENC(${JWT_ISSUER})
    private-key: ENC(${JWT_PRIVATE_KEY})
    public-key: ENC(${JWT_PUBLIC_KEY})
    access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
    refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}

# R2BDC
r2dbc:
  profiles:
    # mobile_cs DB
    - name: mobile_cs
      url: r2dbc:mysql://ENC(${DB_MOBILE_CS_HOST}):ENC(${DB_MOBILE_CS_PORT})/ENC(${DB_MOBILE_CS_DATABASE})?sslMode=DISABLED&serverZoneId=Asia/Seoul
      username: ENC(${DB_MOBILE_CS_USER})
      password: ENC(${DB_MOBILE_CS_PASSWORD})
      pool:
        initial-size: 2
        max-size: 2
        max-create-connection-time: 15s
        max-idle-time: 15s
        max-life-time: 1m
        validation-query: SELECT 1
    - name: example_read
      url: r2dbc:mysql://ENC(${DB_EXAMPLE_READ_HOST}):ENC(${DB_EXAMPLE_READ_PORT})/ENC(${DB_EXAMPLE_READ_DATABASE})?sslMode=DISABLED&serverZoneId=Asia/Seoul
      username: ENC(${DB_EXAMPLE_READ_USER})
      password: ENC(${DB_EXAMPLE_READ_PASSWORD})
      pool:
        initial-size: 2
        max-size: 3
        max-create-connection-time: 15s
        max-idle-time: 15s
        max-life-time: 1m
        validation-query: SELECT 1

    - name: example_write
      url: r2dbc:mysql://ENC(${DB_EXAMPLE_CUD_HOST}):ENC(${DB_EXAMPLE_CUD_PORT})/ENC(${DB_EXAMPLE_CUD_DATABASE})?sslMode=DISABLED&serverZoneId=Asia/Seoul
      username: ENC(${DB_EXAMPLE_CUD_USER})
      password: ENC(${DB_EXAMPLE_READ_PASSWORD})
      pool:
        initial-size: 2
        max-size: 3
        max-create-connection-time: 15s
        max-idle-time: 15s
        max-life-time: 1m
        validation-query: SELECT 1

#Jasypt
jasypt:
  encryptor:
    bean: secretKeyEnvJasypt
    property:
      detector-bean: secretKeyEnvJasypt

# OpenAPI Document
springdoc:
  api-docs:
    enabled: true
    path: /docs
    version: OPENAPI_3_1
  auto-tag-classes: false
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  packages-to-scan: io.happytalk
  swagger-ui:
    # swagger-ui 사용시 api-docs.version 을 OPENAPI_3_0 으로 설정
    enabled: false
    path: /swagger-ui
  webjars:
    prefix: ""
